# Bluesky Summary Newsletter Configuration

# Bluesky API Configuration
bluesky:
  username: "${BLUESKY_USERNAME}"  # Your Bluesky username (e.g., user.bsky.social)
  password: "${BLUESKY_PASSWORD}"  # Your Bluesky password or app password

# Bluesky users to monitor (full handles like user.bsky.social)
bluesky_users:
  - "shamsbot.bsky.social"
  - "passanthalbot.bsky.social"

# AI Configuration
ai:
  provider: "groq"  # or "openai" or "anthropic"
  models:  # Models to try in order (best to worst)
    - "llama-3.3-70b-versatile"     # Best for complex structured tasks
    - "qwen-2.5-32b"               # Good for reasoning and structured outputs  
    - "llama-3.1-70b-versatile"    # Good balance of performance and speed
    - "llama-3.1-8b-instant"       # Fast but less capable (final fallback)
  base_url: "https://api.groq.com/openai/v1"  # Groq API URL

# Email Configuration
email:
  smtp_server: "smtp.gmail.com"
  smtp_port: 587
  sender_email: "${EMAIL_SENDER_EMAIL}"  # Set in .env file
  sender_password: "${EMAIL_SENDER_PASSWORD}"  # Set in .env file
  recipient_emails: "${EMAIL_RECIPIENTS}"  # Comma-separated list in .env file
  subject: "Daily Bluesky Summary"

# General Settings
settings:
  hours_lookback: 24  # How many hours back to fetch posts
  max_posts_per_user: 50  # Maximum posts to fetch per user