# Bluesky Summary Newsletter Configuration

# Bluesky API Configuration
bluesky:
  username: "${BLUESKY_USERNAME}"  # Your Bluesky username (e.g., user.bsky.social)
  password: "${BLUESKY_PASSWORD}"  # Your Bluesky password or app password

# Bluesky users to monitor (full handles like user.bsky.social)
bluesky_users:
  - "shamsbot.bsky.social"

# AI Configuration
ai:
  provider: "groq"  # or "openai" or "anthropic"
  model: "llama3-8b-8192"  # Available models: llama3-8b-8192, llama3-70b-4096, mixtral-8x7b-32768
  base_url: "https://api.groq.com/openai/v1/"  # Groq API URL

# Email Configuration
email:
  smtp_server: "smtp.gmail.com"
  smtp_port: 587
  sender_email: "tnevespestana@gmail.com"
  sender_password: "${EMAIL_SENDER_PASSWORD}"  # Set in .env file
  recipient_emails:
    - "tnpestana@hotmail.com"
  subject: "Daily Bluesky Summary"

# General Settings
settings:
  hours_lookback: 24  # How many hours back to fetch posts
  max_posts_per_user: 50  # Maximum posts to fetch per user