name: Daily Bluesky Newsletter

on:
  schedule:
    # Run every day at 7:00 AM UTC (adjust as needed)
    - cron: '0 7 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  send-newsletter:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create .env file from secrets
      run: |
        echo "BLUESKY_USERNAME=${{ secrets.BLUESKY_USERNAME }}" >> .env
        echo "BLUESKY_PASSWORD=${{ secrets.BLUESKY_PASSWORD }}" >> .env
        echo "EMAIL_SENDER_EMAIL=${{ secrets.EMAIL_SENDER_EMAIL }}" >> .env
        echo "EMAIL_SENDER_PASSWORD=${{ secrets.EMAIL_SENDER_PASSWORD }}" >> .env
        echo "EMAIL_RECIPIENTS=${{ secrets.EMAIL_RECIPIENTS }}" >> .env
        echo "GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}" >> .env
    
    - name: Run newsletter script
      run: |
        set -e
        echo "Starting newsletter generation..."
        python src/main.py
        echo "Newsletter script completed successfully"
    
    - name: Clean up
      run: rm -f .env